- name: "Generate new data in /etc/hosts {{inventory_hostname}}"
  local_action: "shell python3 ../src/helper.py generate_hosts_file_dict"
  register: result

- name: "Config was generated"
  debug:
    msg: "{{ result.stdout }}"

- name: "Set fact hosts_file_array"
  set_fact:
    hosts_file_dict: "{{ result.stdout }}"

- name: "Removing old values from /etc/hosts file"
  lineinfile:
   path: /etc/hosts
   regexp: "{{ item.key }}"
   state: absent
  with_dict: "{{hosts_file_dict.data}}"
  when: hosts_file_dict.success

- name: "Setting new values into /etc/hosts file"
  lineinfile:
   path: /etc/hosts
   line: "{{ item.value }} {{ item.key}}"
  with_dict: "{{hosts_file_dict.data}}"
  when: hosts_file_dict.success

