ansible_python_interpreter: /usr/bin/python3
SETTINGS: "{{ lookup('file', '../settings.json') | from_json }}"
DEFAULTS: "{{ lookup('file', SETTINGS['CONFIGS_DIRECTORY'].replace('${HOME}', lookup('env', 'HOME')) + '/defaults.json') | from_json }}"
ITEM_CONFIG: "{{ lookup('file', SETTINGS['CONFIGS_DIRECTORY'].replace('${HOME}', lookup('env', 'HOME')) + 'configuration_items/{{ inventory_hostname }}.json') | from_json }}"
KEY_REPLACE_STATS: "{{ lookup('file', SETTINGS['CONFIGS_DIRECTORY'].replace('${HOME}', lookup('env', 'HOME')) + 'key_replace_stats.json') | from_json }}"
CONFIG: "{{ DEFAULTS | combine (ITEM_CONFIG) | combine (KEY_REPLACE_STATS)}}"
